version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vercel-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5400:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: